# Generated by Django 5.2.5 on 2025-08-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0003_contact_delete_members_delete_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
