# Generated by Django 5.2.5 on 2025-08-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0007_featured_houses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_registers',
        ),
    ]
